// timezoneData.js
function populateAllTimezonesData() {
    const timezones = [
        { zone: "Africa/Abidjan", label: "Abidjan, Africa" },
        { zone: "Africa/Accra", label: "Accra, Ghana" },
        { zone: "Africa/Addis_Ababa", label: "Addis Ababa, Ethiopia" },
        { zone: "Africa/Algiers", label: "Algiers, Algeria" },
        { zone: "Africa/Asmara", label: "Asmara, Eritrea" },
        { zone: "Africa/Bamako", label: "Bamako, Mali" },
        { zone: "Africa/Bangui", label: "Bangui, Central African Republic" },
        { zone: "Africa/Banjul", label: "Banjul, Gambia" },
        { zone: "Africa/Bissau", label: "Bissau, Guinea-Bissau" },
        { zone: "Africa/Blantyre", label: "Blantyre, Malawi" },
        { zone: "Africa/Brazzaville", label: "Brazzaville, Congo" },
        { zone: "Africa/Bujumbura", label: "Bujumbura, Burundi" },
        { zone: "Africa/Cairo", label: "Cairo, Egypt" },
        { zone: "Africa/Casablanca", label: "Casablanca, Morocco" },
        { zone: "Africa/Ceuta", label: "Ceuta, Spain (Africa)" },
        { zone: "Africa/Conakry", label: "Conakry, Guinea" },
        { zone: "Africa/Dakar", label: "Dakar, Senegal" },
        { zone: "Africa/Dar_es_Salaam", label: "Dar es Salaam, Tanzania" },
        { zone: "Africa/Djibouti", label: "Djibouti, Djibouti" },
        { zone: "Africa/Douala", label: "Douala, Cameroon" },
        { zone: "Africa/El_Aaiun", label: "El Aaiún, Western Sahara" },
        { zone: "Africa/Freetown", label: "Freetown, Sierra Leone" },
        { zone: "Africa/Gaborone", label: "Gaborone, Botswana" },
        { zone: "Africa/Harare", label: "Harare, Zimbabwe" },
        { zone: "Africa/Johannesburg", label: "Johannesburg, South Africa" },
        { zone: "Africa/Juba", label: "Juba, South Sudan" },
        { zone: "Africa/Kampala", label: "Kampala, Uganda" },
        { zone: "Africa/Khartoum", label: "Khartoum, Sudan" },
        { zone: "Africa/Kigali", label: "Kigali, Rwanda" },
        { zone: "Africa/Kinshasa", label: "Kinshasa, DR Congo" },
        { zone: "Africa/Lagos", label: "Lagos, Nigeria" },
        { zone: "Africa/Libreville", label: "Libreville, Gabon" },
        { zone: "Africa/Lome", label: "Lomé, Togo" },
        { zone: "Africa/Luanda", label: "Luanda, Angola" },
        { zone: "Africa/Lubumbashi", label: "Lubumbashi, DR Congo" },
        { zone: "Africa/Lusaka", label: "Lusaka, Zambia" },
        { zone: "Africa/Malabo", label: "Malabo, Equatorial Guinea" },
        { zone: "Africa/Maputo", label: "Maputo, Mozambique" },
        { zone: "Africa/Maseru", label: "Maseru, Lesotho" },
        { zone: "Africa/Mbabane", label: "Mbabane, Eswatini" },
        { zone: "Africa/Mogadishu", label: "Mogadishu, Somalia" },
        { zone: "Africa/Monrovia", label: "Monrovia, Liberia" },
        { zone: "Africa/Nairobi", label: "Nairobi, Kenya" },
        { zone: "Africa/Ndjamena", label: "N'Djamena, Chad" },
        { zone: "Africa/Niamey", label: "Niamey, Niger" },
        { zone: "Africa/Nouakchott", label: "Nouakchott, Mauritania" },
        { zone: "Africa/Ouagadougou", label: "Ouagadougou, Burkina Faso" },
        { zone: "Africa/Porto-Novo", label: "Porto-Novo, Benin" },
        { zone: "Africa/Sao_Tome", label: "São Tomé, Sao Tome and Principe" },
        { zone: "Africa/Tripoli", label: "Tripoli, Libya" },
        { zone: "Africa/Tunis", label: "Tunis, Tunisia" },
        { zone: "Africa/Windhoek", label: "Windhoek, Namibia" },

        { zone: "America/Adak", label: "Adak, USA (Hawaii-Aleutian)" },
        { zone: "America/Anchorage", label: "Anchorage, USA (Alaska Time)" },
        { zone: "America/Anguilla", label: "Anguilla" },
        { zone: "America/Antigua", label: "Antigua" },
        { zone: "America/Araguaina", label: "Araguaína, Brazil" },
        { zone: "America/Argentina/Buenos_Aires", label: "Buenos Aires, Argentina" },
        { zone: "America/Argentina/Catamarca", label: "Catamarca, Argentina" },
        { zone: "America/Argentina/Cordoba", label: "Cordoba, Argentina" },
        { zone: "America/Argentina/Jujuy", label: "Jujuy, Argentina" },
        { zone: "America/Argentina/La_Rioja", label: "La Rioja, Argentina" },
        { zone: "America/Argentina/Mendoza", label: "Mendoza, Argentina" },
        { zone: "America/Argentina/Rio_Gallegos", label: "Rio Gallegos, Argentina" },
        { zone: "America/Argentina/Salta", label: "Salta, Argentina" },
        { zone: "America/Argentina/San_Juan", label: "San Juan, Argentina" },
        { zone: "America/Argentina/San_Luis", label: "San Luis, Argentina" },
        { zone: "America/Argentina/Tucuman", label: "Tucuman, Argentina" },
        { zone: "America/Argentina/Ushuaia", label: "Ushuaia, Argentina" },
        { zone: "America/Aruba", label: "Aruba" },
        { zone: "America/Asuncion", label: "Asunción, Paraguay" },
        { zone: "America/Atikokan", label: "Atikokan, Canada" },
        { zone: "America/Bahia", label: "Bahia, Brazil" },
        { zone: "America/Bahia_Banderas", label: "Bahía de Banderas, Mexico" },
        { zone: "America/Barbados", label: "Barbados" },
        { zone: "America/Belem", label: "Belém, Brazil" },
        { zone: "America/Belize", label: "Belize" },
        { zone: "America/Blanc-Sablon", label: "Blanc-Sablon, Canada" },
        { zone: "America/Boa_Vista", label: "Boa Vista, Brazil" },
        { zone: "America/Bogota", label: "Bogota, Colombia" },
        { zone: "America/Boise", label: "Boise, USA (Mountain Time)" },
        { zone: "America/Cambridge_Bay", label: "Cambridge Bay, Canada" },
        { zone: "America/Campo_Grande", label: "Campo Grande, Brazil" },
        { zone: "America/Cancun", label: "Cancún, Mexico" },
        { zone: "America/Caracas", label: "Caracas, Venezuela" },
        { zone: "America/Cayenne", label: "Cayenne, French Guiana" },
        { zone: "America/Cayman", label: "Cayman Islands" },
        { zone: "America/Chicago", label: "Chicago, USA (Central Time)" },
        { zone: "America/Chihuahua", label: "Chihuahua, Mexico" },
        { zone: "America/Ciudad_Juarez", label: "Ciudad Juárez, Mexico" },
        { zone: "America/Costa_Rica", label: "San Jose, Costa Rica" },
        { zone: "America/Cuiaba", label: "Cuiabá, Brazil" },
        { zone: "America/Curacao", label: "Curaçao" },
        { zone: "America/Danmarkshavn", label: "Danmarkshavn, Greenland" },
        { zone: "America/Dawson", label: "Dawson, Canada (Yukon Time)" },
        { zone: "America/Dawson_Creek", label: "Dawson Creek, Canada" },
        { zone: "America/Denver", label: "Denver, USA (Mountain Time)" },
        { zone: "America/Detroit", label: "Detroit, USA (Eastern Time)" },
        { zone: "America/Dominica", label: "Dominica" },
        { zone: "America/Edmonton", label: "Edmonton, Canada (Mountain Time)" },
        { zone: "America/Eirunepe", label: "Eirunepé, Brazil" },
        { zone: "America/El_Salvador", label: "El Salvador" },
        { zone: "America/Fort_Nelson", label: "Fort Nelson, Canada" },
        { zone: "America/Fortaleza", label: "Fortaleza, Brazil" },
        { zone: "America/Glace_Bay", label: "Glace Bay, Canada" },
        { zone: "America/Goose_Bay", label: "Goose Bay, Canada" },
        { zone: "America/Grand_Turk", label: "Grand Turk, Turks & Caicos" },
        { zone: "America/Grenada", label: "Grenada" },
        { zone: "America/Guadeloupe", label: "Guadeloupe" },
        { zone: "America/Guatemala", label: "Guatemala" },
        { zone: "America/Guayaquil", label: "Guayaquil, Ecuador" },
        { zone: "America/Guyana", label: "Guyana" },
        { zone: "America/Halifax", label: "Halifax, Canada (Atlantic Time)" },
        { zone: "America/Havana", label: "Havana, Cuba" },
        { zone: "America/Hermosillo", label: "Hermosillo, Mexico" },
        { zone: "America/Indiana/Indianapolis", label: "Indianapolis, USA (Eastern Time)" },
        { zone: "America/Indiana/Knox", label: "Knox, USA (Central Time)" },
        { zone: "America/Indiana/Marengo", label: "Marengo, USA (Eastern Time)" },
        { zone: "America/Indiana/Petersburg", label: "Petersburg, USA (Eastern Time)" },
        { zone: "America/Indiana/Vevay", label: "Vevay, USA (Eastern Time)" },
        { zone: "America/Indiana/Vincennes", label: "Vincennes, USA (Eastern Time)" },
        { zone: "America/Indiana/Winamac", label: "Winamac, USA (Eastern Time)" },
        { zone: "America/Inuvik", label: "Inuvik, Canada" },
        { zone: "America/Iqaluit", label: "Iqaluit, Canada" },
        { zone: "America/Jamaica", label: "Jamaica" },
        { zone: "America/Juneau", label: "Juneau, USA (Alaska Time)" },
        { zone: "America/Kentucky/Louisville", label: "Louisville, USA (Eastern Time)" },
        { zone: "America/Kentucky/Monticello", label: "Monticello, USA (Eastern Time)" },
        { zone: "America/La_Paz", label: "La Paz, Bolivia" },
        { zone: "America/Lima", label: "Lima, Peru" },
        { zone: "America/Los_Angeles", label: "Los Angeles, USA (Pacific Time)" },
        { zone: "America/Maceio", label: "Maceió, Brazil" },
        { zone: "America/Managua", label: "Managua, Nicaragua" },
        { zone: "America/Manaus", label: "Manaus, Brazil" },
        { zone: "America/Marigot", label: "Marigot, St Martin" },
        { zone: "America/Martinique", label: "Martinique" },
        { zone: "America/Matamoros", label: "Matamoros, Mexico" },
        { zone: "America/Mazatlan", label: "Mazatlán, Mexico" },
        { zone: "America/Menominee", label: "Menominee, USA" },
        { zone: "America/Merida", label: "Mérida, Mexico" },
        { zone: "America/Metlakatla", label: "Metlakatla, USA" },
        { zone: "America/Mexico_City", label: "Mexico City, Mexico" },
        { zone: "America/Miquelon", label: "Miquelon, St Pierre & Miquelon" },
        { zone: "America/Moncton", label: "Moncton, Canada" },
        { zone: "America/Monterrey", label: "Monterrey, Mexico" },
        { zone: "America/Montevideo", label: "Montevideo, Uruguay" },
        { zone: "America/Montserrat", label: "Montserrat" },
        { zone: "America/Nassau", label: "Nassau, Bahamas" },
        { zone: "America/New_York", label: "New York, USA (Eastern Time)" },
        { zone: "America/Nome", label: "Nome, USA (Alaska Time)" },
        { zone: "America/Noronha", label: "Fernando de Noronha, Brazil" },
        { zone: "America/North_Dakota/Beulah", label: "Beulah, USA" },
        { zone: "America/North_Dakota/Center", label: "Center, USA" },
        { zone: "America/North_Dakota/New_Salem", label: "New Salem, USA" },
        { zone: "America/Nuuk", label: "Nuuk, Greenland" },
        { zone: "America/Ojinaga", label: "Ojinaga, Mexico" },
        { zone: "America/Panama", label: "Panama City, Panama" },
        { zone: "America/Paramaribo", label: "Paramaribo, Suriname" },
        { zone: "America/Phoenix", label: "Phoenix, USA (MST)" },
        { zone: "America/Port-au-Prince", label: "Port-au-Prince, Haiti" },
        { zone: "America/Port_of_Spain", label: "Port of Spain, Trinidad & Tobago" },
        { zone: "America/Porto_Velho", label: "Porto Velho, Brazil" },
        { zone: "America/Puerto_Rico", label: "San Juan, Puerto Rico" },
        { zone: "America/Punta_Arenas", label: "Punta Arenas, Chile" },
        { zone: "America/Rankin_Inlet", label: "Rankin Inlet, Canada" },
        { zone: "America/Recife", label: "Recife, Brazil" },
        { zone: "America/Regina", label: "Regina, Canada (CST, no DST)" },
        { zone: "America/Resolute", label: "Resolute, Canada" },
        { zone: "America/Rio_Branco", label: "Rio Branco, Brazil" },
        { zone: "America/Santarem", label: "Santarém, Brazil" },
        { zone: "America/Santiago", label: "Santiago, Chile" },
        { zone: "America/Santo_Domingo", label: "Santo Domingo, Dominican Republic" },
        { zone: "America/Sao_Paulo", label: "Sao Paulo, Brazil" },
        { zone: "America/Scoresbysund", label: "Scoresbysund, Greenland" },
        { zone: "America/Sitka", label: "Sitka, USA (Alaska Time)" },
        { zone: "America/St_Barthelemy", label: "St. Barthélemy" },
        { zone: "America/St_Johns", label: "St. John's, Canada (Newfoundland)" },
        { zone: "America/St_Kitts", label: "St. Kitts" },
        { zone: "America/St_Lucia", label: "St. Lucia" },
        { zone: "America/St_Thomas", label: "St. Thomas" },
        { zone: "America/St_Vincent", label: "St. Vincent" },
        { zone: "America/Swift_Current", label: "Swift Current, Canada" },
        { zone: "America/Tegucigalpa", label: "Tegucigalpa, Honduras" },
        { zone: "America/Thule", label: "Thule, Greenland" },
        { zone: "America/Tijuana", label: "Tijuana, Mexico" },
        { zone: "America/Toronto", label: "Toronto, Canada (Eastern Time)" },
        { zone: "America/Tortola", label: "Tortola" },
        { zone: "America/Vancouver", label: "Vancouver, Canada (Pacific Time)" },
        { zone: "America/Whitehorse", label: "Whitehorse, Canada" },
        { zone: "America/Winnipeg", label: "Winnipeg, Canada (Central Time)" },
        { zone: "America/Yakutat", label: "Yakutat, USA (Alaska Time)" },
        { zone: "America/Yellowknife", label: "Yellowknife, Canada" },

        { zone: "Antarctica/Casey", label: "Casey, Antarctica" },
        { zone: "Antarctica/Davis", label: "Davis, Antarctica" },
        { zone: "Antarctica/DumontDUrville", label: "Dumont D'Urville, Antarctica" },
        { zone: "Antarctica/Macquarie", label: "Macquarie Island, Australia" },
        { zone: "Antarctica/Mawson", label: "Mawson, Antarctica" },
        { zone: "Antarctica/McMurdo", label: "McMurdo, Antarctica" },
        { zone: "Antarctica/Palmer", label: "Palmer, Antarctica" },
        { zone: "Antarctica/Rothera", label: "Rothera, Antarctica" },
        { zone: "Antarctica/Syowa", label: "Syowa, Antarctica" },
        { zone: "Antarctica/Troll", label: "Troll, Antarctica" },
        { zone: "Antarctica/Vostok", label: "Vostok, Antarctica" },

        { zone: "Asia/Almaty", label: "Almaty, Kazakhstan" },
        { zone: "Asia/Amman", label: "Amman, Jordan" },
        { zone: "Asia/Anadyr", label: "Anadyr, Russia (ANAT)" },
        { zone: "Asia/Aqtau", label: "Aqtau, Kazakhstan" },
        { zone: "Asia/Aqtobe", label: "Aqtobe, Kazakhstan" },
        { zone: "Asia/Ashgabat", label: "Ashgabat, Turkmenistan" },
        { zone: "Asia/Atyrau", label: "Atyrau, Kazakhstan" },
        { zone: "Asia/Baghdad", label: "Baghdad, Iraq" },
        { zone: "Asia/Bahrain", label: "Bahrain" },
        { zone: "Asia/Baku", label: "Baku, Azerbaijan" },
        { zone: "Asia/Bangkok", label: "Bangkok, Thailand" },
        { zone: "Asia/Barnaul", label: "Barnaul, Russia" },
        { zone: "Asia/Beirut", label: "Beirut, Lebanon" },
        { zone: "Asia/Bishkek", label: "Bishkek, Kyrgyzstan" },
        { zone: "Asia/Brunei", label: "Brunei" },
        { zone: "Asia/Chita", label: "Chita, Russia" },
        { zone: "Asia/Choibalsan", label: "Choibalsan, Mongolia" },
        { zone: "Asia/Colombo", label: "Colombo, Sri Lanka" },
        { zone: "Asia/Damascus", label: "Damascus, Syria" },
        { zone: "Asia/Dhaka", label: "Dhaka, Bangladesh" },
        { zone: "Asia/Dili", label: "Dili, Timor-Leste" },
        { zone: "Asia/Dubai", label: "Dubai, UAE" },
        { zone: "Asia/Dushanbe", label: "Dushanbe, Tajikistan" },
        { zone: "Asia/Famagusta", label: "Famagusta, Cyprus" },
        { zone: "Asia/Gaza", label: "Gaza, Palestine" },
        { zone: "Asia/Hebron", label: "Hebron, Palestine" },
        { zone: "Asia/Ho_Chi_Minh", label: "Ho Chi Minh City, Vietnam" },
        { zone: "Asia/Hong_Kong", label: "Hong Kong, China" },
        { zone: "Asia/Hovd", label: "Hovd, Mongolia" },
        { zone: "Asia/Irkutsk", label: "Irkutsk, Russia (IRKT)" },
        { zone: "Asia/Jakarta", label: "Jakarta, Indonesia" },
        { zone: "Asia/Jayapura", label: "Jayapura, Indonesia" },
        { zone: "Asia/Jerusalem", label: "Jerusalem, Israel" },
        { zone: "Asia/Kabul", label: "Kabul, Afghanistan" },
        { zone: "Asia/Kamchatka", label: "Kamchatka, Russia (PETT)" },
        { zone: "Asia/Karachi", label: "Karachi, Pakistan" },
        { zone: "Asia/Kathmandu", label: "Kathmandu, Nepal" },
        { zone: "Asia/Khandyga", label: "Khandyga, Russia" },
        { zone: "Asia/Calcutta", label: "Kolkata, India" },
        { zone: "Asia/Krasnoyarsk", label: "Krasnoyarsk, Russia (KRAT)" },
        { zone: "Asia/Kuala_Lumpur", label: "Kuala Lumpur, Malaysia" },
        { zone: "Asia/Kuching", label: "Kuching, Malaysia" },
        { zone: "Asia/Kuwait", label: "Kuwait City, Kuwait" },
        { zone: "Asia/Macau", label: "Macau, China" },
        { zone: "Asia/Magadan", label: "Magadan, Russia (MAGT)" },
        { zone: "Asia/Makassar", label: "Makassar, Indonesia" },
        { zone: "Asia/Manila", label: "Manila, Philippines" },
        { zone: "Asia/Muscat", label: "Muscat, Oman" },
        { zone: "Asia/Nicosia", label: "Nicosia, Cyprus" },
        { zone: "Asia/Novokuznetsk", label: "Novokuznetsk, Russia" },
        { zone: "Asia/Novosibirsk", label: "Novosibirsk, Russia (NOVT)" },
        { zone: "Asia/Omsk", label: "Omsk, Russia (OMST)" },
        { zone: "Asia/Oral", label: "Oral, Kazakhstan" },
        { zone: "Asia/Phnom_Penh", label: "Phnom Penh, Cambodia" },
        { zone: "Asia/Pontianak", label: "Pontianak, Indonesia" },
        { zone: "Asia/Pyongyang", label: "Pyongyang, North Korea" },
        { zone: "Asia/Qatar", label: "Doha, Qatar" },
        { zone: "Asia/Qostanay", label: "Qostanay, Kazakhstan" },
        { zone: "Asia/Qyzylorda", label: "Qyzylorda, Kazakhstan" },
        { zone: "Asia/Yangon", label: "Yangon, Myanmar" }, 
        { zone: "Asia/Riyadh", label: "Riyadh, Saudi Arabia" },
        { zone: "Asia/Sakhalin", label: "Sakhalin, Russia" },
        { zone: "Asia/Samarkand", label: "Samarkand, Uzbekistan" },
        { zone: "Asia/Seoul", label: "Seoul, South Korea" },
        { zone: "Asia/Shanghai", label: "Shanghai, China" },
        { zone: "Asia/Singapore", label: "Singapore, Singapore" },
        { zone: "Asia/Srednekolymsk", label: "Srednekolymsk, Russia" },
        { zone: "Asia/Taipei", label: "Taipei, Taiwan" },
        { zone: "Asia/Tashkent", label: "Tashkent, Uzbekistan" },
        { zone: "Asia/Tbilisi", label: "Tbilisi, Georgia" },
        { zone: "Asia/Tehran", label: "Tehran, Iran" },
        { zone: "Asia/Thimphu", label: "Thimphu, Bhutan" },
        { zone: "Asia/Tokyo", label: "Tokyo, Japan" },
        { zone: "Asia/Tomsk", label: "Tomsk, Russia" },
        { zone: "Asia/Ulaanbaatar", label: "Ulaanbaatar, Mongolia" },
        { zone: "Asia/Urumqi", label: "Urumqi, China (Unofficial Xinjiang Time)" },
        { zone: "Asia/Ust-Nera", label: "Ust-Nera, Russia" },
        { zone: "Asia/Vladivostok", label: "Vladivostok, Russia" },
        { zone: "Asia/Yakutsk", label: "Yakutsk, Russia" },
        { zone: "Asia/Yekaterinburg", label: "Yekaterinburg, Russia" },
        { zone: "Asia/Yerevan", label: "Yerevan, Armenia" },

        { zone: "Atlantic/Azores", label: "Azores" },
        { zone: "Atlantic/Bermuda", label: "Bermuda" },
        { zone: "Atlantic/Canary", label: "Canary Islands, Spain" },
        { zone: "Atlantic/Cape_Verde", label: "Praia, Cape Verde" },
        { zone: "Atlantic/Faroe", label: "Tórshavn, Faroe Islands" },
        { zone: "Atlantic/Madeira", label: "Madeira, Portugal" },
        { zone: "Atlantic/Reykjavik", label: "Reykjavik, Iceland" },
        { zone: "Atlantic/South_Georgia", label: "South Georgia" },
        { zone: "Atlantic/St_Helena", label: "St. Helena" },
        { zone: "Atlantic/Stanley", label: "Stanley, Falkland Islands" },

        { zone: "Australia/Adelaide", label: "Adelaide, Australia (ACST/ACDT)" },
        { zone: "Australia/Brisbane", label: "Brisbane, Australia (AEST)" },
        { zone: "Australia/Broken_Hill", label: "Broken Hill, Australia" },
        { zone: "Australia/Darwin", label: "Darwin, Australia (ACST)" },
        { zone: "Australia/Eucla", label: "Eucla, Australia" },
        { zone: "Australia/Hobart", label: "Hobart, Australia (AEST/AEDT)" },
        { zone: "Australia/Lindeman", label: "Lindeman, Australia" },
        { zone: "Australia/Lord_Howe", label: "Lord Howe Island, Australia" },
        { zone: "Australia/Melbourne", label: "Melbourne, Australia (AEST/AEDT)" },
        { zone: "Australia/Perth", label: "Perth, Australia (AWST)" },
        { zone: "Australia/Sydney", label: "Sydney, Australia (AEST/AEDT)" },

        { zone: "Europe/Amsterdam", label: "Amsterdam, Netherlands" },
        { zone: "Europe/Andorra", label: "Andorra" },
        { zone: "Europe/Astrakhan", label: "Astrakhan, Russia" },
        { zone: "Europe/Athens", label: "Athens, Greece" },
        { zone: "Europe/Belgrade", label: "Belgrade, Serbia" },
        { zone: "Europe/Berlin", label: "Berlin, Germany" },
        { zone: "Europe/Bratislava", label: "Bratislava, Slovakia" },
        { zone: "Europe/Brussels", label: "Brussels, Belgium" },
        { zone: "Europe/Bucharest", label: "Bucharest, Romania" },
        { zone: "Europe/Budapest", label: "Budapest, Hungary" },
        { zone: "Europe/Chisinau", label: "Chisinau, Moldova" },
        { zone: "Europe/Copenhagen", label: "Copenhagen, Denmark" },
        { zone: "Europe/Dublin", label: "Dublin, Ireland" },
        { zone: "Europe/Gibraltar", label: "Gibraltar" },
        { zone: "Europe/Helsinki", label: "Helsinki, Finland" },
        { zone: "Europe/Istanbul", label: "Istanbul, Turkey" },
        { zone: "Europe/Kaliningrad", label: "Kaliningrad, Russia (FET)" },
        { zone: "Europe/Kyiv", label: "Kyiv, Ukraine" },  
        { zone: "Europe/Kirov", label: "Kirov, Russia" },
        { zone: "Europe/Lisbon", label: "Lisbon, Portugal" },
        { zone: "Europe/Ljubljana", label: "Ljubljana, Slovenia" },
        { zone: "Europe/London", label: "London, UK (GMT/BST)" },
        { zone: "Europe/Luxembourg", label: "Luxembourg" },
        { zone: "Europe/Madrid", label: "Madrid, Spain" },
        { zone: "Europe/Malta", label: "Malta" },
        { zone: "Europe/Minsk", label: "Minsk, Belarus" },
        { zone: "Europe/Monaco", label: "Monaco" },
        { zone: "Europe/Moscow", label: "Moscow, Russia (MSK)" },
        { zone: "Europe/Oslo", label: "Oslo, Norway" },
        { zone: "Europe/Paris", label: "Paris, France (CET/CEST)" },
        { zone: "Europe/Podgorica", label: "Podgorica, Montenegro" },
        { zone: "Europe/Prague", label: "Prague, Czechia" },
        { zone: "Europe/Riga", label: "Riga, Latvia" },
        { zone: "Europe/Rome", label: "Rome, Italy" },
        { zone: "Europe/Samara", label: "Samara, Russia (SAMT)" },
        { zone: "Europe/San_Marino", label: "San Marino" },
        { zone: "Europe/Sarajevo", label: "Sarajevo, Bosnia & Herzegovina" },
        { zone: "Europe/Saratov", label: "Saratov, Russia" },
        { zone: "Europe/Simferopol", label: "Simferopol, Ukraine/Russia" },
        { zone: "Europe/Skopje", label: "Skopje, North Macedonia" },
        { zone: "Europe/Sofia", label: "Sofia, Bulgaria" },
        { zone: "Europe/Stockholm", label: "Stockholm, Sweden" },
        { zone: "Europe/Tallinn", label: "Tallinn, Estonia" },
        { zone: "Europe/Tirane", label: "Tirane, Albania" },
        { zone: "Europe/Ulyanovsk", label: "Ulyanovsk, Russia" },
        { zone: "Europe/Uzhgorod", label: "Uzhgorod, Ukraine" },
        { zone: "Europe/Vaduz", label: "Vaduz, Liechtenstein" },
        { zone: "Europe/Vatican", label: "Vatican City" },
        { zone: "Europe/Vienna", label: "Vienna, Austria" },
        { zone: "Europe/Vilnius", label: "Vilnius, Lithuania" },
        { zone: "Europe/Volgograd", label: "Volgograd, Russia" },
        { zone: "Europe/Warsaw", label: "Warsaw, Poland" },
        { zone: "Europe/Zagreb", label: "Zagreb, Croatia" },
        { zone: "Europe/Zaporozhye", label: "Zaporozhye, Ukraine" },
        { zone: "Europe/Zurich", label: "Zurich, Switzerland" },

        { zone: "Indian/Antananarivo", label: "Antananarivo, Madagascar" },
        { zone: "Indian/Chagos", label: "Chagos, British Indian Ocean Territory" },
        { zone: "Indian/Christmas", label: "Christmas Island" },
        { zone: "Indian/Cocos", label: "Cocos Islands" },
        { zone: "Indian/Comoro", label: "Comoro, Comoros" },
        { zone: "Indian/Kerguelen", label: "Kerguelen, French Southern & Antarctic Lands" },
        { zone: "Indian/Mahe", label: "Mahé, Seychelles" },
        { zone: "Indian/Maldives", label: "Malé, Maldives" },
        { zone: "Indian/Mauritius", label: "Port Louis, Mauritius" },
        { zone: "Indian/Mayotte", label: "Mayotte" },
        { zone: "Indian/Reunion", label: "Réunion" },

        { zone: "Pacific/Apia", label: "Apia, Samoa" },
        { zone: "Pacific/Auckland", label: "Auckland, New Zealand" },
        { zone: "Pacific/Bougainville", label: "Bougainville, Papua New Guinea" },
        { zone: "Pacific/Chatham", label: "Chatham, New Zealand" },
        { zone: "Pacific/Chuuk", label: "Chuuk, Micronesia" },
        { zone: "Pacific/Easter", label: "Easter Island, Chile" },
        { zone: "Pacific/Efate", label: "Efate, Vanuatu" },
        { zone: "Pacific/Fakaofo", label: "Fakaofo, Tokelau" },
        { zone: "Pacific/Fiji", label: "Suva, Fiji" },
        { zone: "Pacific/Funafuti", label: "Funafuti, Tuvalu" },
        { zone: "Pacific/Galapagos", label: "Galapagos, Ecuador" },
        { zone: "Pacific/Gambier", label: "Gambier, French Polynesia" },
        { zone: "Pacific/Guadalcanal", label: "Guadalcanal, Solomon Islands" },
        { zone: "Pacific/Guam", label: "Hagåtña, Guam" },
        { zone: "Pacific/Honolulu", label: "Honolulu, USA (Hawaii Time)" },
        { zone: "Pacific/Kiritimati", label: "Kiritimati, Kiribati" },
        { zone: "Pacific/Kosrae", label: "Kosrae, Micronesia" },
        { zone: "Pacific/Majuro", label: "Majuro, Marshall Islands" },
        { zone: "Pacific/Marquesas", label: "Marquesas, French Polynesia" },
        { zone: "Pacific/Midway", label: "Midway Island, USA" },
        { zone: "Pacific/Nauru", label: "Nauru" },
        { zone: "Pacific/Niue", label: "Niue" },
        { zone: "Pacific/Norfolk", label: "Norfolk Island" },
        { zone: "Pacific/Noumea", label: "Noumea, New Caledonia" },
        { zone: "Pacific/Pago_Pago", label: "Pago Pago, American Samoa" },
        { zone: "Pacific/Palau", label: "Palau" },
        { zone: "Pacific/Pitcairn", label: "Pitcairn Island" },
        { zone: "Pacific/Pohnpei", label: "Pohnpei, Micronesia" },
        { zone: "Pacific/Port_Moresby", label: "Port Moresby, Papua New Guinea" },
        { zone: "Pacific/Rarotonga", label: "Rarotonga, Cook Islands" },
        { zone: "Pacific/Saipan", label: "Saipan, Northern Mariana Islands" },
        { zone: "Pacific/Tahiti", label: "Tahiti, French Polynesia" },
        { zone: "Pacific/Tarawa", label: "Tarawa, Kiribati" },
        { zone: "Pacific/Tongatapu", label: "Nukuʻalofa, Tonga" },
        { zone: "Pacific/Wake", label: "Wake Island, USA" },
        { zone: "Pacific/Wallis", label: "Wallis, Wallis & Futuna" },

        { zone: "UTC", label: "Coordinated Universal Time (UTC)" }
    ];

    setAllTimezones(timezones);
}